dist: xenial
sudo: false

language: java

jdk:
  - oraclejdk11
  
  - openjdk8
  - openjdk10
  - openjdk11
  
  
install:

    - mvn install
    - mvn dependency:tree
    - env
    - mvn clean install -Dgeppetto  # Test version for use with Geppetto...
    - mvn dependency:tree -Dgeppetto
