dist: xenial
sudo: false

language: java

jdk:
  - oraclejdk11
  
  - openjdk8
  - openjdk10
  - openjdk11
  
  
install:

    - mvn install
    - mvn dependency:tree
    - mvn clean
    - mvn install -P geppetto  # Test version for use with Geppetto...
