# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:  [ master, development, experimental, osb* ]
  pull_request:
    branches:  [ master, development, experimental, osb* ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11']
      fail-fast: False

    name: Test on Java ${{ matrix.Java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'temurin'
    - name: Test with Maven
      run: mvn install
    - name: Further tests
      run: |
        pwd
        ls -alt
        mvn dependency:tree
